# **Generalized Linear Models**

### **Components:**

- Random Component
- Systematic Component
- Link Function

### **Common Distributions:**

- **Normal Distribution:**
	- Continuous Data
	- Accept All Possible Value in (-inf, +inf)
	- Bell Shape Curve Centered Aroung the Mean
	- Constant Variance
 
- **Binomial Distribution:**
	- Binary or Porportion Data

- **Poisson Distribution:**
	- Count Data
	- Discrete
	- Right-Skewed
	- Suitable for Counting Rare Events

- **Negative Binomial Distribution:**
	- Count Data
	- Discrete
	- Right-Skewed
	- More Flexible than Poisson
	- Suitable for Count Data with Overdispersion

- **Gamma Distribution:**
	- Continuous
	- Right-Skewed

- **Log-Transformed Normal:**
	- Continuous
	- Right-Skewed

### **Common Link Functions:**

- **Identity:**
	- for Normal Distribution
	- When the random variable can take any value in the real number line

- **Logit:**
	- for Binary Classification
	- When the random variable is a probability or proportion

- **Log:**
	- for Poisson Distribution, Gamma Distribution
	- When the random variable is positive

- **Inverse:**
	- for Gamma Distribution
	- When the random variable is positive and the effect of predictors are multiplicative

### **Approach:**

1. Plot the distribution of the target variable and compare it to distributions plots. Collect knowledge about the target variable (for example it's a counting data, binary data, ...). Select best suited distribution/distributions for the target variable. At the end you should compare the results for different random variables.

2. Select suitable link function.

### **Models:**

- Linear Regression
- Logistic Regression ✅
- Probit Regression ✅
- Ordinal Regression
- Poisson Regression
- Gamma Regression
- ...

In [1]:
# study different GLMs implemented in scikit-learn

## **Logistic Regression:**

- **Random Component:** Bernoulli or Binomial (for multinomial classification) Distribution
- **Link Function:** Logit Function
- **Systematic Component:** Linear Predictor

This king of GLM is suitable for classifying the binary target variable or we can use some techniques to do multinomial calssification using logistic regression.

**Multinomial Classification Approaches:**
- One Vs. Rest Approach
- Softmax Approach

In [58]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.datasets import load_breast_cancer, load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV, validation_curve, learning_curve
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.multiclass import OneVsRestClassifier

In [52]:
data = load_breast_cancer()
X, y = data.data, data.target

assert X.shape == (569, 30)
assert y.shape == (569, )
print("data loaded successfully.")

data loaded successfully.

In [20]:
df = pd.concat(
    [
        pd.DataFrame(X, columns=data.feature_names),
        pd.Series(y, name="target")
	],
    axis=1
)
df

     mean radius  mean texture  ...  worst fractal dimension  target
0          17.99         10.38  ...                  0.11890       0
1          20.57         17.77  ...                  0.08902       0
2          19.69         21.25  ...                  0.08758       0
3          11.42         20.38  ...                  0.17300       0
4          20.29         14.34  ...                  0.07678       0
..           ...           ...  ...                      ...     ...
564        21.56         22.39  ...                  0.07115       0
565        20.13         28.25  ...                  0.06637       0
566        16.60         28.08  ...                  0.07820       0
567        20.60         29.33  ...                  0.12400       0
568         7.76         24.54  ...                  0.07039       1

[569 rows x 31 columns]

In [21]:
# train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# scaling the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [23]:
# model training 
logreg = LogisticRegression(
    C=np.inf,
    class_weight=None, # set it to 'balanced' to compare the results
    random_state=42,
    l1_ratio=0, # by default it has l2 regularization
)

logreg.fit(X_train_scaled, y_train)

LogisticRegression(C=inf, l1_ratio=0, random_state=42)

In [35]:
sign_status = []
for coef in logreg.coef_.ravel():
    if coef > 0:
        sign_status.append("positive")
    elif coef == 0:
        sign_status.append("zero")
    elif coef < 0:
        sign_status.append("negative")

coefficient_df = pd.DataFrame(
    data=abs(logreg.coef_.ravel()), columns=["coef"]
)
coefficient_df['sign'] = sign_status
coefficient_df.sort_values(by="coef", ascending=False).reset_index(names="feature_ID")

    feature_ID        coef      sign
0            5  274.940098  positive
1            7  266.184736  negative
2           10  259.639462  negative
3           16  246.608093  positive
4           26  244.059711  negative
5           28  169.654855  negative
6            9  168.017946  negative
7           13  167.389401  negative
8            6  134.838158  negative
9           19  131.939234  positive
10          12  115.350114  positive
11          20  105.871360  negative
12          23  103.736690  negative
13          15   97.574130  negative
14          18   95.954186  positive
15          24   93.974962  positive
16          21   91.921276  negative
17          14   79.540060  negative
18          22   73.018745  positive
19          17   70.051654  negative
20          29   59.683836  positive
21           8   40.996505  positive
22           2   40.020926  positive
23          11   35.917928  positive
24          25   29.285376  positive
25           1   16.986388  negative
26           3   10.890150  positive
27           0    9.433096  positive
28          27    8.908160  negative
29           4    5.033443  positive

In [38]:
# model training 
logreg_l2 = LogisticRegression(
    C=1, # inverse regularization strength
    class_weight=None, # set it to 'balanced' to compare the results
    random_state=42,
    l1_ratio=0, # by default it has l2 regularization
)

logreg_l2.fit(X_train_scaled, y_train)

sign_status = []
for coef in logreg_l2.coef_.ravel():
    if coef > 0:
        sign_status.append("positive")
    elif coef == 0:
        sign_status.append("zero")
    elif coef < 0:
        sign_status.append("negative")

coefficient_df = pd.DataFrame(
    data=abs(logreg_l2.coef_.ravel()), columns=["coef"]
)
coefficient_df['sign'] = sign_status
coefficient_df.sort_values(by="coef", ascending=False).reset_index(names="feature_ID")

    feature_ID      coef      sign
0           21  1.350606  negative
1           10  1.268178  negative
2           28  1.208200  negative
3            7  1.119804  negative
4           26  0.943053  negative
5           13  0.907186  negative
6           20  0.879840  negative
7           23  0.841846  negative
8            6  0.801458  negative
9           27  0.778217  negative
10          15  0.682491  positive
11          19  0.616230  positive
12          12  0.610583  negative
13          22  0.589453  negative
14          24  0.544170  negative
15           5  0.540164  positive
16          18  0.500425  positive
17           3  0.465210  negative
18           0  0.431904  negative
19           2  0.393432  negative
20           1  0.387326  negative
21          14  0.313307  negative
22          17  0.311300  negative
23           8  0.236119  positive
24          11  0.188877  positive
25          16  0.175275  positive
26          29  0.157414  negative
27           9  0.075921  positive
28           4  0.071667  negative
29          25  0.016110  positive

In [42]:
# model training 
logreg_l1 = LogisticRegression(
    C=1, # inverse regularization strength
    class_weight=None, # set it to 'balanced' to compare the results
    random_state=42,
    l1_ratio=1, # by default it has l2 regularization
    solver="liblinear"
)

logreg_l1.fit(X_train_scaled, y_train)

sign_status = []
for coef in logreg_l1.coef_.ravel():
    if coef > 0:
        sign_status.append("positive")
    elif coef == 0:
        sign_status.append("zero")
    elif coef < 0:
        sign_status.append("negative")

coefficient_df = pd.DataFrame(
    data=abs(logreg_l1.coef_.ravel()), columns=["coef"]
)
coefficient_df['sign'] = sign_status
coefficient_df.sort_values(by="coef", ascending=False).reset_index(names="feature_ID")

    feature_ID      coef      sign
0           23  3.122343  negative
1           10  2.470136  negative
2            7  2.437017  negative
3           21  1.854182  negative
4           26  1.298469  negative
5           28  1.032401  negative
6           15  0.894132  positive
7           20  0.762839  negative
8           18  0.459953  positive
9           14  0.432847  negative
10          11  0.384591  positive
11          19  0.277513  positive
12          24  0.165887  negative
13           8  0.017226  positive
14          13  0.000000      zero
15          12  0.000000      zero
16           6  0.000000      zero
17           9  0.000000      zero
18           2  0.000000      zero
19           3  0.000000      zero
20           4  0.000000      zero
21           5  0.000000      zero
22           1  0.000000      zero
23           0  0.000000      zero
24          16  0.000000      zero
25          17  0.000000      zero
26          25  0.000000      zero
27          22  0.000000      zero
28          27  0.000000      zero
29          29  0.000000      zero

In [49]:
y_pred = logreg.predict(X_test_scaled)
y_pred_l2 = logreg_l2.predict(X_test_scaled)
y_pred_l1 = logreg_l1.predict(X_test_scaled)

score = f1_score(y_test, y_pred)
score_l2 = f1_score(y_test, y_pred_l2)
score_l1 = f1_score(y_test, y_pred_l1)

score, score_l2, score_l1

(0.948905109489051, 0.9790209790209791, 0.9787234042553191)

In [54]:
# multiclass classification using logistic regression (one vs. rest approach)
# loading data
data = load_iris()
X, y = data.data, data.target

# train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=42, random_state=42
)

# scaling inputs
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# model training
loreg = LogisticRegression(
    random_state=42
)
ovr_clf = OneVsRestClassifier(estimator=logreg, n_jobs=-1)

ovr_clf.fit(X_train_scaled, y_train)

OneVsRestClassifier(estimator=LogisticRegression(C=inf, l1_ratio=0,
                                                 random_state=42),
                    n_jobs=-1)

In [57]:
# multiclass classification using logistic regression (softmax approach)
# loading data
data = load_iris()
X, y = data.data, data.target

# train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=42, random_state=42
)

# scaling inputs
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# model training
loreg = LogisticRegression(
    random_state=42
)
logreg.fit(X_train_scaled, y_train)

LogisticRegression(C=inf, l1_ratio=0, random_state=42)